server:
    port: 8081
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/springCare
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    data:
        web:
            pageable:
                page-parameter: pagina
                size-parameter: tamanho
            sort:
                sort-parameter: ordem
